name: Generate Manifest Matrix
description: Action that returns a matrix of repository, manifest path, package name tuples, suitable to be passed to build-ci entrypoint inputs.
author: Tommy Gatti
inputs:
  packages:
    required: true
    description: Space-separated list of spack packages to generate matrix entries for.
  packages-root-dir:
    required: true
    description: Path relative to ACCESS-NRI/access-spack-packages, for the package repository root.
  ref:
    required: true
    description: Ref for the fallback access-spack-packages repository to checkout
outputs:
  matrix:
    description: |
      A GitHub Actions matrix of repository, manifest path, and package name tuples.
    value: ${{ steps.gen.outputs.matrix }}
runs:
  using: composite
  steps:
    - name: Checkout fallback repository
      uses: actions/checkout@v6
      with:
        repository: ACCESS-NRI/access-spack-packages
        ref: ${{ inputs.ref }}

    - name: Generate matrix
      id: gen
      # Get all packages that will be tested, then
      # Get file paths to manifests for each package, first from the package git repository,
      # then from this repository's package-specific manifests, and finally from defaults, then
      # Convert into a JSON array for the matrix, one of the form:
      # [
      #   {"template_value": "mom5", "repository": "ACCESS-NRI/MOM5", "ref": "main", "filepath": ".github/build-ci/manifests/intel.spack.yaml.j2"},
      #   {"template_value": "mom5", "repository": "ACCESS-NRI/MOM5", "ref": "main", "filepath": ".github/build-ci/manifests/gcc.spack.yaml.j2"},
      #   {"template_value": "cice5", "repository": "ACCESS-NRI/access-spack-packages", "ref": "api-v2", "filepath": ".github/build-ci/manifests/cice5/spack.yaml.j2"},
      #   ...
      # ]
      shell: bash
      run: |
        pkgs="${{ inputs.packages }}"

        for pkg in $pkgs; do
          # We want each manifest to have an associated injection of {{ package }} to $pkg
          # Replace underscores with hyphens for the template value, as spack converts directory underscores to package name hyphens
          template_value="${pkg//_/-}"
          package_file="${{ inputs.packages-root-dir }}/$pkg/package.py"

          # Extract `git = "..."` class variable from package.py if present.
          git_url=$(sed -nE "s/^\s*git\s*=\s*['\"]([^'\"]+)['\"].*$/\1/p" "$package_file" | head -n 1)

          if [[ -n "$git_url" ]]; then
            # Extract OWNER/REPO from HTTPS git URL
            # Example: https://github.com/OWNER/REPO.git
            repository=$(echo "$git_url" | sed -E 's|^https://.*/([^/]+)/([^.]+?)(\.git)?$|\1/\2|')
            cloned_repo_path=$(mktemp -d "${RUNNER_TEMP}/package-manifest-repo-${pkg}-XXXXXX")

            if git clone --depth 1 --filter=blob:none --quiet "$git_url" "$cloned_repo_path"; then
              repo_manifest_root="$cloned_repo_path/"
              if [[ -d "$repo_manifest_root" ]]; then
                # Use any manifests from the package's source repository first.
                cd $cloned_repo_path
                manifest_paths=$(find .github/build-ci/manifests -iname '*.j2' -type f -printf '%p ')
                ref=$(git branch --show-current)
                cd -
              fi
            fi
          fi

          if [[ -z "${manifest_paths:-}" && -d ".github/build-ci/manifests/$pkg" ]]; then  # Look for specific manifests for the package
            # We space-separate the paths as we later use them in a for loop
            manifest_paths=$(find ".github/build-ci/manifests/$pkg" -iname '*.j2' -type f -printf '%p ')
            repository="access-nri/access-spack-packages"
            ref=${{ inputs.ref }}
          fi

          if [[ -z "${manifest_paths:-}" ]]; then  # Use the default templates if no specific manifests exist for the package
            # Similarly, space-separate the paths for a later for loop. Default manifests are always directly under .github/build-ci/manifests
            manifest_paths=$(find ".github/build-ci/manifests" -maxdepth 1 -iname '*.j2' -type f -printf '%p ')
            repository="access-nri/access-spack-packages"
            ref=${{ inputs.ref }}
          fi

          for manifest_path in $manifest_paths; do
            json_entry=$(printf '{"template_value": "%s", "repository": "%s", "ref": "%s", "filepath": "%s"}' "$template_value" "$repository" "$ref" "$manifest_path")
            json_entries+="${json_entry},"
          done
          unset manifest_paths git_url cloned_repo_path repo_manifest_root
        done

        echo "$json_entries"

        # Remove the trailing comma and wrap in square brackets
        echo "matrix=[${json_entries%,}]" >> $GITHUB_OUTPUT