# These are sensible defaults for manifests as part of build-ci, and can be overridden
repos:
  # Local paths require a directory with a repos.yaml - doesn't respect
  # git-based spack-repo-index.yaml!
  access_spack_packages: $CALLER_REPOSITORY_PATH/spack_repo/access/nri
  # If you want to add a custom builtin ref (if you were testing both a change
  # to access-spack-packages and builtin), you can add the following:
  # builtin:
  #   git: https://github.com/ACCESS-NRI/upstream-spack-packages.git
  #   branch: BRANCH
  #   destination: $env/package-repos/spack-packages
