# All of the package requirements defined here are overridable in environments
packages:
  # Common packages versions
  #cmake:
  #  require:
  #  - '@3.31.6'
  #python:
  #  require:
  #  - '@3.12.13'
  #openmpi:
  #  require:
  #  - '@5.0.8'

  # Common base compiler versions
  gcc:
    require:
    - '@13.2.0'
  intel-oneapi-compilers-classic:
    require:
    - '@2021.10.0'
  intel-oneapi-compilers:
    require:
    - '@2025.2.0'
